# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoStream' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoStream
  pod 'AlamofireImage', '~> 3.2.0'
  
  target 'PhotoStreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoStreamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
